[package]
name = "interoperable_vector_demo_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.3", default-features = false }
interoperable_vector = { path = "../interoperable_vector", features = ["bevy-support"]}
